Add `mindir` format support.
lutzroeder/netron pull request #1227
Opened 2024-02-18 04:06 UTC by Ethan-Chen-plus

🤗👋Hi! We have added our `.mindir` format. Please review our commit.

2024-02-18 17:07 UTC, lutzroeder commented
@Ethan-Chen-plus can you provide some context:
* What is mindir, what problem is it solving and for how many users?
* Why is a new format needed given there are many similar formats?
* Create a script in `./tools` following the patterns used for other frameworks to recreate the `-proto` file.
* Add a test to `./test/models.json` and share an index of 50+ existing files in this format.

2024-03-29 11:30 UTC, Ethan-Chen-plus commented
```ps
PS I:\netron> npm run validate
eslint
pylint
test
gguf/phi-2.Q2_K.gguf
onnx/candy.onnx
keras/1151.4.keras
coreml/Exermote.mlmodel
pytorch/alexnet.ptl
pytorch/DCGAN2.pt
tf/conv-layers.pb.zip
tflite/mobilenet_v1_0.75_160_quantized.tflite
tflite/squeezenet.tflite
```
I have updated my code, please review.
@lutzroeder

2024-03-30 02:26 UTC, lutzroeder commented
@Ethan-Chen-plus can you provide some context:

* What is mindir, what problem is it solving and for how many users?
* Why is a new format needed given there are many similar formats?
* Please rebase to latest `main`.
* The `./tools` scripts should generate regenerate to files from the original `.proto`. When changing the format or generator for `-proto.js` or `-metadata.json` these files should automatically get regenerated from the original source when running `./tools/mindir sync schema metadata`.

2024-04-24 08:42 UTC, Ethan-Chen-plus commented
@lutzroeder Thank you again and we have updated our code. And let me introduce some background infomation:

- What is mindir, what problem is it solving and for how many users?
MindIR (MindSpore IR) is a graph-based functional Intermediate Representation (IR) format developed for the MindSpore framework by Huawei. Its primary purpose is to define the logical structure of networks and the attributes of operators, facilitating the decoupling of model files from hardware platforms through a unified IR. This supports a train-once, deploy-multiple-times paradigm. A key advantage of the MindIR format is its ability to store network structures and weight parameter values, enabling deployment for inference tasks on cloud-based Serving and edge-oriented Lite platforms. The same MindIR file can be deployed across various hardware types, including Ascend AI processors, GPUs, and CPUs.

The user base for the MindIR format primarily comprises researchers, developers, and enterprises needing to deploy AI models across multiple hardware platforms. Given its compatibility with diverse hardware including Ascend AI processors, GPUs, and CPUs, MindIR is particularly well-suited for applications that require deployment both in the cloud and on edge devices. For instance, MindIR can be utilized in Huawei's Atlas 200/300/500 inference products, which are specifically designed for edge AI processing scenarios.

-Why is a new format needed given there are many similar formats?

Compared to other similar IR formats such as ONNX and AIR, MindIR presents unique advantages and application scenarios. ONNX (Open Neural Network Exchange) is a universal format designed for the expression of machine learning models, primarily used for model transfer between different frameworks or on inference engines like TensorRT. AIR (Ascend Intermediate Representation), defined by Huawei, is an open file format tailored for machine learning to better accommodate Huawei AI processors, typically used for inference tasks on Ascend 310. MindIR, on the other hand, is a functional IR based on graph representation. It not only defines an extensible graph structure and operator IR representations but also eliminates model discrepancies across different backends. It is generally used for cross-platform inference tasks, such as executing inference on Ascend 310, GPUs, and MindSpore Lite for models trained on Ascend 910.

2024-04-29 02:18 UTC, Ethan-Chen-plus commented
@lutzroeder Hello.👋 I noticed that eslint failed. Could you please tell me which config file eslint is using? I'll make the necessary fixes based on that config file. Thank you!

2024-05-05 05:01 UTC, Ethan-Chen-plus commented
Requires approval, thank you🤗

2024-05-24 02:44 UTC, Ethan-Chen-plus commented
Workflow requires approval, thank you again🤗

2024-05-27 15:26 UTC, lutzroeder requested changes
> Compared to other similar IR formats such as ...

This format looks very similar to ONNX. Instead of defining a new format, can this be accomplished by using `metadata` extensions in ONNX to augment with additional information.

There is also an existing MindSpore Lite format and a dozen other formats that look similar in principle. Consider a path that leverages existing formats or standards instead of creating another duplicate format that needs to be maintained.

2024-05-27 15:26 UTC, lutzroeder commented on tools/mindir
> +    curl --silent --location --output "./third_party/source/mindspore/mindspore/mindir/schema/mind_ir-metadata.json" "https://raw.githubusercontent.com/Ethan-Chen-plus/mindir/main/mind_ir-metadata.js
The metadata file should not be downloaded from an external location and instead be updated in place as part of `./tools/mindir metadata`.

2024-05-27 15:26 UTC, lutzroeder commented on source/view.js
> +        this.register('./mslite', ['.ms']);
* Resolve incorrect merge

2024-05-27 15:26 UTC, lutzroeder commented on source/mind_ir-metadata.json
> +[
* Rename to `mindir-metadata.json`

2024-05-27 15:26 UTC, lutzroeder commented on source/mind_ir.js
> +/**
Rename to `mindir.js`.

2024-05-27 15:26 UTC, lutzroeder commented on source/mind_ir.js
> +const mind_ir = {
* Rename to `const mindir = {};`.
* Follow pattern in other files that do not predefine empty classes.

2024-05-27 15:26 UTC, lutzroeder commented on source/mind_ir.js
> +export const protobuf = {};
* Remove, this should not be needed.

2024-05-27 15:26 UTC, lutzroeder commented on source/mind_ir.js
> +            return 'mind_ir';
* This has changed in more recent versions. Sync to latest.

2024-05-27 15:26 UTC, lutzroeder commented on source/mind_ir.js
> +mind_ir.Parameter = class {
Renamed in latest. `Parameter` to `Argument` and `Argument` to `Value`.

2024-05-27 15:26 UTC, lutzroeder commented on source/mind_ir.js
> +        this.name = 'SnapML Model Load Error.';
Fix error message.

2024-05-27 15:26 UTC, lutzroeder commented on source/mind_ir.js
> +        this._name = attribute.name;
`Attribute` has been removed in latest and replaced with using `Argument` to represent attribtues.

2024-07-13 03:15 UTC, lutzroeder commented
Closing as stale. Please comment with additional information if the pull request should be reopened.

2024-07-13 03:15 UTC, closed without merging