Update acuity-metadata and support shape inference for more operations
lutzroeder/netron pull request #1317
Opened 2024-07-28 14:32 UTC by hawk081

This PR contains two main changes:
1. Update acuity metadata
2. Support shape inference for more operations

2024-07-28 14:52 UTC, lutzroeder requested changes

2024-07-28 14:52 UTC, lutzroeder commented on source/acuity-metadata.json
> +      { "name": "input0" },
Use readable names for input names.

2024-07-28 14:52 UTC, lutzroeder commented on source/acuity-metadata.json
> +    "constants": [],
Remove empty `"constants": []` and `"attributes: []`.

2024-07-28 14:52 UTC, lutzroeder commented on source/acuity-metadata.json
> +    "category": "Layer",
Follow the category patterns in other files. `Layer` is used Convolution, LSTM or Fully Connected layers.

2024-07-29 15:33 UTC, hawk081 commented
Updated.

2024-07-30 05:41 UTC, hawk081 commented
merged by 17b35c5014b51838b081cd4a47c96bfe47747925

2024-07-30 05:41 UTC, closed without merging