Acuity models support
lutzroeder/netron pull request #614
Opened 2020-10-13 14:29 UTC by hawk081

Hi,

This patch enables the support of Acuity models, please help to review the patch, any suggestions are welcome.

Acuity is an AI framework that can convert the models of other framework(such as tensorflow, tflite, caffe, onnx, etc) to Acuity models, then generate high performance code for embedded platforms.

`.json` file is the Acuity model file which contains the model structure, and `.data` file will be loaded for weights and biases, `.quantize` file is for quanzation parameters. the output tensors' shape of each layer will be inferred if the input shape(s) are provied in model files.

Some popular models converted by Acuity can be found here: https://verisilicon.github.io/acuity-models/

Thanks.

2020-11-09 01:43 UTC, hawk081 commented
Hi Lutz,

Is there anything need to be modified ?

Thanks.

2020-11-09 03:12 UTC, lutzroeder requested changes
1. There are multiple similar formats for deep learning models already. Can Acuity use an existing format instead of creating another duplicate format?
2. `jsyaml` should not be checked in as obfuscated code. For JSON, Protocol Buffers and FlatBuffers are custom implementation using `base.TextDecoder` is checked in. A similar approach should be followed for YAML. Note that using JSON and YAML and Pickle (3 different formats) for a single model is a fragile design. Ideally there should be no YAML dependency.

2020-11-09 03:15 UTC, lutzroeder commented
- [ ] There are dozens of similar formats for deep learning models already. Can Acuity use an existing format instead of investing yet another one?
- [ ] `jsyaml` should not be checked in as obfuscated code. For JSON, Protocol Buffers and FlatBuffers there are custom implementations for Netron and a similar approach would be needed for YAML. Using JSON and YAML and binary (3 different formats) for a single model is a fragile design. Ideally there should be no YAML dependency.

2020-11-09 03:17 UTC, lutzroeder requested changes
- [ ] There are dozens of similar formats for deep learning models already. Can Acuity use an existing format instead of investing yet another one?
- [ ] `jsyaml` should not be checked in as obfuscated code. For JSON, Protocol Buffers and FlatBuffers there are custom implementations for Netron and a similar approach would be needed for YAML. Using JSON and YAML and binary (3 different formats) for a single model is a fragile design. Ideally there should be no YAML dependency.

2020-11-09 03:17 UTC, lutzroeder commented on test/models.json
> +    "source": "https://raw.githubusercontent.com/VeriSilicon/acuity-models/master/models/inception_v1/inception_v1.json",
The file is sorted alphabetically by `type`. This is only testing the JSON code, not the YAML and binary readers. Please add a more comprehensive sample.

2020-11-11 13:36 UTC, hawk081 commented
Thanks!

1. Current format of `.json`, `.data` and `.quantize` are used in our production, It is difficult to migrate to other formats.
2. We will follow the `JSON` to implement a YAML parser.
3. For some historical reasons, we have to use these 3 files to describe the model for now.

2020-11-28 18:53 UTC, lutzroeder commented
> Current format of .json, .data and .quantize are used in our production, It is difficult to migrate to other formats.

It will only get more difficult over time. This is an overcomplicated design with lots of moving parts. Better to fix it early one while you still can. Ideally you should consider what value the framework actually provides and if it does need yet another new file format or can just use an existing one.

2020-12-09 04:33 UTC, hawk081 commented
Thanks for your suggestions.

I will remove the code of loading .quantize and .data, let netron just handle the model structure.

2020-12-22 08:31 UTC, lutzroeder commented
Why is this format needed? There are a dozen other deep learning formats that are more or less identical.

2020-12-22 08:40 UTC, lutzroeder commented
Why is this format needed? There are a dozen other deep learning formats that are more or less identical.

2020-12-22 08:40 UTC, closed without merging

2020-12-22 15:04 UTC, hawk081 commented
Thanks! When we started the project at 2016, there weren't suitable formats for us. so ...